Initial version of Pmod SSR driver with basic on/off control via GPIO
grisp/grisp pull request #141
Opened 2024-09-24 18:01 UTC by bchassoul

This PR introduces the initial version of the Pmod SSR (Solid State Relay) driver for GRiSP boards (`grisp-base` and `grisp2`). The driver enables control of a solid-state relay using a single GPIO pin by switching the relay on `pmod_ssr:on/0` and off `pmod_ssr:off/0`.

Here you can find the Pmod [reference manual](https://digilent.com/reference/pmod/pmodssr/reference-manual)

2024-09-25 09:02 UTC, GwendalLaurent requested changes
Nice PR 👍 

My comments are just small details

2024-10-01 16:40 UTC, bchassoul commented on src/pmod_ssr.erl
> +% '''
Good point, I made the following test with the `pmod_ssr` connected:
```
(oscillator@grisp_oscillator)1> pmod_ssr:on().
pmod_ssr:on().
ok
(oscillator@grisp_oscillator)2> pmod_ssr:on().
pmod_ssr:on().
ok
(oscillator@grisp_oscillator)3> pmod_ssr:on().
pmod_ssr:on().
ok
(oscillator@grisp_oscillator)4> pmod_ssr:off().
pmod_ssr:off().
ok
(oscillator@grisp_oscillator)5> pmod_ssr:off().
pmod_ssr:off().
ok
(oscillator@grisp_oscillator)6> ```

2024-10-01 16:41 UTC, bchassoul commented on src/pmod_ssr.erl
> +        {grisp2, gpio1} -> ok;
ah very nice! yes that would allow to connect over `gpio2` in `grisp_base`

2024-10-02 07:40 UTC, GwendalLaurent requested changes

2024-10-02 07:40 UTC, GwendalLaurent commented on src/pmod_ssr.erl
>      Pin1 = grisp_gpio:open(gpio1_1, #{mode => {output, 0}}),
If the user uses the Slot `{grisp_base, gpio2}` . You will still open `gpio1_1` for `Pin1` but if I understand the docs correctly, you should open `gpio2_1` instead

2024-10-02 07:43 UTC, GwendalLaurent commented on src/pmod_ssr.erl
> +% '''
Did you observe anything special/unexpected on the hardware side ? (e.g. between the first and second `on/0` the current briefly stopped)

2024-10-11 19:25 UTC, merged