MTDS driver
grisp/grisp pull request #151
Opened 2024-12-31 02:49 UTC by ecpeterson

Here's a driver for the MTDS module. It implements only a small subset of the C++ MTDS driver's functionalities, but it's a representative subset: I think any other desired feature could be finding where the C++ driver constructs the relevant payloads and copy-pasting the routines I've written with the protocol constants changed. Functionality which _is_ covered includes relaying touch events to interested Erlang-side applications, drawing lines, printing text, setting color options, and double-buffering (although I did not test this last one).

I also included two demos:

1. `mtds_hello`: Writes "Hello, World!" in green text at the top-left corner of the screen. Based off of `MtdsDemo1.pde:MtdsTest21`.
2. `mtds_sketch`: An Erlang server which listens for touch events and converts them into draw events, so you can draw on the screen with your finger.

Sample run of the two included demos:
```
1> pmod_mtds:start_link(spi2).
{ok,<0.314.0>}
2> mtds_sketch:start_link().
{ok,<0.317.0>}
% scribbled 'GRiSP' with my finger
3> gen_server:stop(pid(0,317,0)).
ok
% needed to release the display handle
4> mtds_hello:run().
ok
% printed 'Hello, World!' in green text in the corner
5> mtds_sketch:start_link().
{ok,<0.321.0>}
% back to scribbling
```

2025-01-02 19:40 UTC, bchassoul requested changes
Hi Eric, nice PR! 👍
My comments are just small details, we use `Edoc` for documentation across the codebase, so would you mind updating the documentation to follow the `Edoc` style for consistency?

I haven’t tested it with the `Pmod`, but from reviewing the code, I couldn’t find any additional issue

2025-01-02 19:40 UTC, bchassoul commented on src/grisp_spi.erl
> +-export_type([ref/0, bus/0]).
Types `ref/0`, `bus/0` are already exported in lines 105 and 110 respectively

2025-01-03 02:55 UTC, ecpeterson commented
I've never edoc-ed before, so I've only done my best to mimic what I saw elsewhere. Hope this satisfies.

Thanks for the review!

2025-01-11 19:01 UTC, ecpeterson commented on src/pmod_mtds.erl
> +-export([poll_loop/1]).  % private
I'd exported it because I felt it made the `spawn_link` call during initialization look nicer. If exporting too much is objectionable, it's just as easy to `spawn_link` there via an anonymous function.

2025-01-11 19:03 UTC, ecpeterson commented on src/pmod_mtds.erl
> +-export([poll_loop/1]).  % private
I'd exported this because I felt it made the `spawn_link` during initialization look nicer. If it's objectionable to over-export, I can get by with an anonymous function there.

2025-01-11 19:11 UTC, ecpeterson commented on src/pmod_mtds.erl
> +    {ok, Interface, 0}.
It's more habit than really careful reasoning: blocking calls in `init` also block any parent supervision tree from making progress with the rest of its own boot, so I was taught to move those out of the way. I don't really know how reliably / quickly the MTDS comes up, so I followed the same pattern.

2025-01-11 19:15 UTC, ecpeterson commented
Thanks for the review. I made the more trivial PR changes; I'll follow up with the others later this weekend.

2025-01-12 15:41 UTC, ecpeterson commented on src/pmod_mtds.erl
> +% TODO: This crashes with error code 0x81.  Don't know why or what that means.
Oh, nice. I'm not going to, but I left a comment about where we could properly parse these other status codes.

2025-01-12 15:42 UTC, ecpeterson commented on src/pmod_mtds.erl
> +-type command() :: 0..63 .
I was resistant to writing a bunch of macros which are each use in one place, but it is actually useful to have them arranged in a table. Done.

2025-01-12 15:46 UTC, ecpeterson commented on src/pmod_mtds.erl
> +-define(CLASS_GRAPHICS, 2#10).
I decided against doing this: the C++ driver's constants are arranged because they insist on being byte-aligned, but the packet header is best understood as <<:2, :6>> or <<:2, :14>> depending on the first two bits, which makes their constants a bit unnatural. I did take this as motivation to get straight about how these constants 'ought' to be presented, which I hope also clears up your other question about that `class()` type. As a compromise, I also put the C++ driver's names for these constants as comments in the Erlang driver, which is pretty lightweight and will solve the problem of cross-referencing.

2025-01-12 15:46 UTC, ecpeterson commented on src/pmod_mtds.erl
> +%     comamnds??) which are **not** supported by the device firmware.
I started doing this in the constants header file, which is a nice centralized place to record these misses.

2025-01-12 15:47 UTC, ecpeterson commented on src/pmod_mtds.erl
> +-type class() :: 0..3 .
I'm going to mark this resolved to consolidate conversation in the thread below about `CLASS_UTILITY`.

2025-01-12 23:31 UTC, ecpeterson commented
Alright: ready for re-review, I think.

2025-01-15 08:35 UTC, GwendalLaurent commented on src/pmod_mtds.erl
> +    {ok, Interface, 0}.
I understand your point of view. However, in our case, we want to add the the driver to the device supervision tree only after a full and correct initialization of the pmod and its driver. I would move the initialization instruction done after the timeout back into the `init/1` function

2025-01-16 04:46 UTC, ecpeterson commented on src/pmod_mtds.erl
> +    {ok, Interface, 0}.
I'm not convinced, but I agree that this is beyond the scope of this PR and I should just do whatever the other device drivers do. I've moved the whole of bring-up into `init/1`. (I also just learned about `handle_continue/2`, which is better than the outdated abuse of timeouts!)

2025-01-17 15:07 UTC, GwendalLaurent approved these changes

2025-01-31 14:40 UTC, odo commented
Hey @bchassoul, any chance of a review? Would love to use a touch display on my GRiSP board 8)

2025-01-31 15:51 UTC, ziopio commented on examples/mtds/mtds_sketch.erl
> +% @doc Demonstration of MTDS touch events.
You may rebase your branch and PR on latest master HEAD. You can test if the docs build successfully with `rebar3 ex_doc`

2025-02-02 22:42 UTC, ecpeterson commented on examples/mtds/mtds_sketch.erl
> +% @doc Demonstration of MTDS touch events.
Rebased + updated, hope it's to your liking

2025-02-03 08:45 UTC, ziopio approved these changes

2025-02-03 08:49 UTC, merged